### ISSUE TITLE
Genesis creation

### ISSUE THREAD

**Issue by zgreat** [mit-dci/CryptoKernel#11]
Hello again I see you have made good progress on this project. :smile: 
Just a quick question I should change bool newGenesisBlock to true and run ./ckd to generate a new genesis correct or am I missing something? It doesn't seem to work

**Comment by metalicjames** [comment]
If you remove the existing genesis block file and have no existing block database ckd will generate a new genesis block for you.

Which version of ck are you using?

**Comment by zgreat** [comment]
Ahh I didn't remove the block genesis file. That worked cheers mate!
