### ISSUE TITLE
Failed to load lz4

### ISSUE THREAD

**Issue by anders94** [mit-dci/CryptoKernel#2]
When compiling on a fresh Ubuntu 16.04.2 LTS Server install, I get this warning:
```
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by //usr/lib/x86_64-linux-gnu/libcurl.so.4, may conflict with libcrypto.so.1.1
```
and after running `./ckd` when syncing I get this presumably at block 5774:
```
Tue Jul 11 14:39:53 2017 INFO Network(): Downloading blocks 5773 to 5973
Tue Jul 11 14:39:54 2017 INFO Network(): Attempting to connect to 18.238.7.30
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load lz4
Aborted (core dumped)
```
`lz4.so` was successfully copied to `/usr/lib` and I ran `ldconfig` (checked to make sure it was configured to look in /usr/lib) for good measure.

Not sure what is depending on lz4, maybe lua? Any hints?

Thanks.

**Comment by metalicjames** [comment]
You can safely ignore the warning about libcrypto, it doesn't seem to cause any issues in my testing. As for lz4, try putting lz4.so in the same directory as ckd.

**Comment by anders94** [comment]
That fixes it. Is there a better solution though?

**Comment by metalicjames** [comment]
Ideally I'd like to get lz4 statically linked into Lua but I've had no success with that thus far. Using the Lua CLI you can see where Lua is searching for dynamic libraries. On my system it looks like this:
`> package.path
/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua`
