### ISSUE TITLE
"blockdb" parameter not honored

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/CryptoKernel#22]
For some reason, when i specify a full path in the "blockdb" parameter of the config.json, it is still writing to the blockdb subdirectory of the working directory, in stead of the actual path configured. The weird thing is when i added a log statement to the Blockchain constructor, it prints out the correct path for ```dbDir``` 

There is also a database in that folder, but it's empty whilst the folder under the working directory keeps growing.

**Comment by anders94** [comment]
Looks like that is being hard-set here:

https://github.com/mit-dci/CryptoKernel/blob/master/src/kernel/blockchain.cpp#L881

I'll pose a PR with a fix.
