### ISSUE TITLE
Mined blocks not accepted on the production network

### ISSUE THREAD

**Issue by anders94** [mit-dci/CryptoKernel#24]
The production network doesn't seem to be accepting newly mined blocks for the past few weeks. Additionally, few production peers from `peers.txt` seem to be accepting connections. (CryptoKernel version 0.1.0-alpha-rc4)

In particular, the public node `18.250.7.224` syncs to block `141,682` but won't accept newly mined blocks beyond that.

I can confirm that a private network with two 0.1.0-alpha-rc4 peers works as expected.

**Comment by metalicjames** [comment]
That's likely because I made some hard forking changes on my end which all of my public nodes are following. I have not published the changes in a binary yet but I will do soon.

**Comment by anders94** [comment]
Thanks.
