### ISSUE TITLE
 Logo Proposal for CryptoKernel

### ISSUE THREAD

**Issue by leonardoderoy** [mit-dci/CryptoKernel#41]
Hello! @mit-dci
I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards
Leonardo Deroy 

Graphic Designer

**Comment by metalicjames** [comment]
Hi Leonardo, 

Thanks for reaching out but we already have a logo designed for CK (albeit not in this repo).
