### ISSUE TITLE
Strange balance

### ISSUE THREAD

**Issue by peterres** [mit-dci/CryptoKernel#7]
Started second ckd instance on another computer. Sent more than 1k of balance to it's address (from another ckd account, height >70k), then first time started this new ckd instance with mining, and checking the status with getinfo I've got a strange balance output at height 6:

(height 2 still 0)
```
ckd getinfo
{
   "balance" : "0.00000000",
   "ck_version" : "0.0.1-alpha",
   "connections" : 1,
   "height" : 2,
   "mempool" : {
      "count" : 0,
      "size" : "0.000 MB"
   },
   "rpc_version" : "2.0.0-dev"
}
```
(and here is the strange balance)
```
ckd getinfo
{
   "balance" : "99.99973893",
   "ck_version" : "0.0.1-alpha",
   "connections" : 1,
   "height" : 6,
   "mempool" : {
      "count" : 0,
      "size" : "0.000 MB"
   },
   "rpc_version" : "2.0.0-dev"
}
```

Seconds after and also all consequent getinfo calls return (correct) balance 0:

(notice same height here)
```
ckd getinfo
{
   "balance" : "0.00000000",
   "ck_version" : "0.0.1-alpha",
   "connections" : 1,
   "height" : 6,
   "mempool" : {
      "count" : 0,
      "size" : "0.000 MB"
   },
   "rpc_version" : "2.0.0-dev"
}
```

(and soon after)
```
ckd getinfo
{
   "balance" : "0.00000000",
   "ck_version" : "0.0.1-alpha",
   "connections" : 1,
   "height" : 11,
   "mempool" : {
      "count" : 0,
      "size" : "0.000 MB"
   },
   "rpc_version" : "2.0.0-dev"
}
```

Any explanation of the strange balance 99.99973893 there?

**Comment by metalicjames** [comment]
It's likely that you mined a block while syncing up (at height 6). The value you received seems like the block reward around then.

**Comment by peterres** [comment]
OK if not a problem that needs to be addressed then let's close this.
