### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by alkavan** [mit-dci/CryptoKernel#79]
Would be nice to have CMake support for this project, I'm already inspecting ways to integrate this, can really be nice with JetBrains tools (CLion)...

**Comment by metalicjames** [comment]
If you're interested in setting that up I'd be happy to merge it. I spent quite a bit of time getting it set up with `premake` though which seems to work well and be a lot simpler than `cmake`. Since we already use Lua for contracts in the project it made sense to use it for the build system as well.

**Comment by alkavan** [comment]
@metalicjames
Yeah, `cmake` is not the easiest to setup, but tends to work very after.

However, for now I'm having an issue with building it, it seems this only can really work on ubuntu, or ubuntu using Docker? I see the file in the `build` directory, any plans on making it make generic, and dropping docker?

I'm on Archlinux, made some instructions to get most of the dependencies, but I do have a strange issue with your other library `selene`. I did find it on AUR, but the "normal" version won't build cause error, and the `selene-git-0.4+131+gffe1ade-1` see to build fine, however I still get:

```
In file included from src/kernel/blockchain.cpp:31:
src/kernel/contract.h:4:10: fatal error: selene.h: No such file or directory
 #include <selene.h>
          ^~~~~~~~~~
```

```
$ locate selene.h
/usr/share/include/selene.h
```
Could this be an issue with the `CryptoKernel` build file?

Here are **most** of the dependencies on arch:
```
sudo pacman -S sfml leveldb argtable readline lua cmake doxygen cppunit openssl microhttpd jsoncpp
sudo aura -As premake-git selene-git
```
I'm also not sure what package is `libcurl4-gnutls-dev` on other systems ...

**Comment by metalicjames** [comment]
Have you tried using the `--include-dir` flag to specify the selene installation directory? e.g. `--include-dir=/usr/share/include`.

I am not familiar with Arch, but libcurl4-gnutls-dev is just curl.
