### ISSUE TITLE
client_key_25519 / server_key_25519

### ISSUE THREAD

**Issue by anders94** [mit-dci/CryptoKernel#88]
How are local keys supposed to be generated? Getting this on the console:
```
keys/client_key_25519.pub: No such file or directory
keys/client_key_25519: No such file or directory
keys/server_key_25519: No such file or directory
```

**Comment by metalicjames** [comment]
Just `mkdir keys` and `ckd` will generate them for you. Once C++17 filesystem support is more widely available in compilers we'll use that to make the directory.

**Comment by anders94** [comment]
:+1:
